# Generated by Django 6.0.2 on 2026-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_coins',
            field=models.IntegerField(default=3),
        ),
    ]
