# Generated by Django 6.0.2 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='skills/videos/'),
        ),
    ]
