# Generated by Django 6.0.2 on 2026-07-31 12:15

import skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_skill_level_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='video',
            field=models.FileField(blank=True, null=True, storage=skills.models.Skill.get_video_storage, upload_to='skills/videos/'),
        ),
    ]
